### PR TITLE
Update the colour for MHCLG

### PR DESCRIPTION
**Pull request by AlanGabbianelli**
The colour is wrong in a few places and they've asked us to update it.

Trello card: 
https://trello.com/c/wqKT3TpE/952-change-mhclgs-brand-colour

### CODE REVIEW

**Comment by stevenjmesser** [comment]
I had no idea that colour was defined here!

**Review by deborahchua — APPROVED** [review]

**Comment by edent** [comment]
I don't think this is the right place... We just copied the Frontend Toolkit when we were running GH pages.

**Comment by deborahchua** [comment]
@edent we have also been updating this across other repos including the Frontend Toolkit, this file probably isn't used but should we update it anyway for consistency?

**Comment by edent** [comment]
Ah! I understand. I don't have write access any more - perhaps @Lawrence-G can merge?

**Comment by Lawrence-G** [comment]
Not sure what we are talking about here or how to achieve the desired outcome but happy to help. click 'merge pull request'?

**Comment by deborahchua** [comment]
Yes please @Lawrence-G - thank you! 😄

**Pull request merged**
