### PR TITLE
Changes to CODE_OF_CONDUCT.md per GDS style guide

### PR DESCRIPTION
**Pull request by subatoi**
Changes to language and style throughout code of conduct to bring in line with GDS style guide (https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style)

### CODE REVIEW

**Review by edent — CHANGES_REQUESTED** [review]
I think

 * religion, sexual identity and orientation

Should be

* religion
* sexual identity and orientation

**Comment by subatoi** [comment]
Agreed @edent. This has been amended in 7a1719667c18a693205d70cc8e47d0c0706f440d

**Comment by arnau** [comment]
Hello, what code of conduct is the reference, the one in this repository or this other one https://github.com/alphagov/code-of-conduct ?

Shouldn't they be aligned?

**Comment by edent** [comment]
@arnau this related to the CoC in this repo. I think @bahmady will be updating the other one.

**Comment by subatoi** [comment]
The other CoC in https://github.com/alphagov/code-of-conduct doesn't fully conform to GDS language style either, but that's a separate repo and not `open-standards`. I think the question is whether it's appropriate for Registers (i.e. @arnau) to use this one even if there are two `alphagov` CoCs which are not aligned, which may be out of the scope of this discussion. 

I will approach the owner of the other CoC. If we can align them then that would surely be the most straightforward solution.

**Pull request merged**
